# Generated by Django 5.2.9 on 2026-04-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webview', '0008_alter_suggestionnotification_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_email',
            field=models.EmailField(blank=True, help_text="Email address to use for notifications in case it's different from the GitHub email", max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='receive_email_notifications',
            field=models.BooleanField(default=False, help_text='Receive an email about new notifications'),
        ),
    ]
