// biome-ignore-all lint/complexity/useLiteralKeys: Schema keys are accessed dynamically on untyped objects
/**
 * Orval input transformer.
 *
 * Cleans up quirks in the OpenAPI spec generated by drf-spectacular that would
 * otherwise produce awkward TypeScript types:
 *
 * - Removes `NullEnum` (a synthetic `enum: [null]` schema that drf-spectacular emits
 *   for nullable enum fields). We replace `oneOf: [EnumRef, NullEnum]` with a simple
 *   `nullable: true` + direct enum reference.
 */
import type { OpenAPIObject } from "openapi3-ts/oas30";

const NULL_ENUM_REF = "#/components/schemas/NullEnum";

/**
 * Recursively walk an object and simplify any `oneOf` that contains a NullEnum ref.
 * Transforms `{ nullable: true, oneOf: [RealEnum, NullEnum] }` into
 * `{ nullable: true, allOf: [RealEnum] }`.
 */
function removeNullEnumRefs(obj: unknown): unknown {
  if (obj === null || typeof obj !== "object") return obj;
  if (Array.isArray(obj)) return obj.map(removeNullEnumRefs);

  const record = obj as Record<string, unknown>;

  // Check if this object has a oneOf containing NullEnum
  if (Array.isArray(record["oneOf"])) {
    const oneOf = record["oneOf"] as Array<Record<string, unknown>>;
    const withoutNull = oneOf.filter((item) => item["$ref"] !== NULL_ENUM_REF);
    if (withoutNull.length < oneOf.length) {
      // Had NullEnum — replace oneOf with allOf (single remaining ref)
      delete record["oneOf"];
      record["allOf"] = withoutNull;
    }
  }

  // Recurse into all values
  for (const key of Object.keys(record)) {
    record[key] = removeNullEnumRefs(record[key]);
  }
  return record;
}

export default (schema: OpenAPIObject): OpenAPIObject => {
  if (!schema.components?.schemas) return schema;

  delete schema.components.schemas["NullEnum"];
  return removeNullEnumRefs(schema) as OpenAPIObject;
};
