# Generated by Django 4.2.16 on 2025-04-16 15:36

from django.db import migrations, models
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0046_alter_cachedsuggestions_proposal'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='cvederivationclusterproposal',
            name='update_update',
        ),
        migrations.AlterField(
            model_name='cvederivationclusterproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('accepted', 'accepted'), ('published', 'published')], default='pending', max_length=9),
        ),
        migrations.AlterField(
            model_name='cvederivationclusterproposalstatusevent',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('accepted', 'accepted'), ('published', 'published')], default='pending', max_length=9),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cvederivationclusterproposal',
            trigger=pgtrigger.compiler.Trigger(
                name='update_update',
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."status" IS DISTINCT FROM (NEW."status"))',
                    func='INSERT INTO "shared_cvederivationclusterproposalstatusevent" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status") VALUES (_pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status"); RETURN NULL;',
                    hash='7422450f03396f4beb556d4e1fcd676a15088d82',
                    operation='UPDATE',
                    pgid='pgtrigger_update_update_b6b2c',
                    table='shared_cvederivationclusterproposal',
                    when='AFTER',
                ),
            ),
        ),
    ]
