# Generated by Django 4.2.24 on 2025-11-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0058_remove_cvederivationclusterproposal_pgpubsub_8c7ef_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvederivationclusterproposal',
            name='comment',
            field=models.CharField(default='', help_text='Optional free text comment for additional notes, context, dismissal reason', max_length=1000),
        ),
    ]
