# Generated by Django 4.2.24 on 2025-11-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0059_cvederivationclusterproposal_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='nixpkgsissue',
            name='comment',
            field=models.CharField(default='', help_text='Optional comment from the suggestion that lead to this issue', max_length=1000),
        ),
    ]
