# Generated by Django 4.2.24 on 2025-12-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0061_nixpkgsissue_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nixpkgsissue',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='nixpkgsissue',
            name='cve',
        ),
        migrations.RemoveField(
            model_name='nixpkgsissue',
            name='description',
        ),
    ]
