# Generated by Django 5.2.6 on 2026-01-05 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0061_nixpkgs_issue_relate_to_suggestion'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='NixDerivationDependencyThrough',
                    fields=[
                        ('pk', models.CompositePrimaryKey('nixderivation_id', 'nixderivationoutput_id', blank=True, editable=False, primary_key=True, serialize=False)),
                        ('nixderivation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.nixderivation')),
                        ('nixderivationoutput', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.nixderivationoutput')),
                    ],
                    options={
                        'db_table': 'shared_nixderivation_dependencies',
                    },
                ),
                migrations.AlterField(
                    model_name='nixderivation',
                    name='dependencies',
                    field=models.ManyToManyField(through='shared.NixDerivationDependencyThrough', to='shared.nixderivationoutput'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE shared_nixderivation_dependencies
                            DROP CONSTRAINT shared_nixderivation_dependencies_pkey,
                            DROP COLUMN id;

                        -- Redundant, since it's caputed by the CompositePrimaryKey's first element
                        DROP INDEX shared_nixderivation_dependencies_nixderivation_id_1e830ca9;

                        -- Run this manually with `CONCURRENTLY` before applying the migration in order to avoid stopping the world:
                        CREATE UNIQUE INDEX IF NOT EXISTS shared_nixderivation_dependencies_pkey_composite
                            ON shared_nixderivation_dependencies (nixderivation_id, nixderivationoutput_id);

                        ALTER TABLE shared_nixderivation_dependencies
                            -- Unfortunately we can't reuse the underlying index because it's bound to the uniqueness constraint
                            DROP CONSTRAINT shared_nixderivation_dep_nixderivation_id_nixderi_7ba267e1_uniq,
                            ADD CONSTRAINT shared_nixderivation_dependencies_pkey_composite
                                PRIMARY KEY USING INDEX shared_nixderivation_dependencies_pkey_composite;
                    """,
                    reverse_sql="""
                        ALTER TABLE shared_nixderivation_dependencies
                            DROP CONSTRAINT shared_nixderivation_dependencies_pkey,
                            -- This will take time!
                            ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

                        -- Run the following two statements manually with `CONCURRENTLY` before applying the rollback in order to avoid stopping the world:
                        CREATE INDEX IF NOT EXISTS shared_nixderivation_dependencies_nixderivation_id_1e830ca9
                            ON shared_nixderivation_dependencies (nixderivation_id);
                        CREATE INDEX IF NOT EXISTS shared_nixderivation_dep_nixderivation_id_nixderi_7ba267e1_uniq
                            ON shared_nixderivation_dependencies (nixderivation_id, nixderivationoutput_id);

                        ALTER TABLE shared_nixderivation_dependencies
                            ADD CONSTRAINT shared_nixderivation_dep_nixderivation_id_nixderi_7ba267e1_uniq
                                UNIQUE (nixderivation_id, nixderivationoutput_id);
                    """,
                ),
            ],
        ),
    ]
