# Generated by Django 4.2.24 on 2025-12-16 11:29

from django.db import migrations
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0062_remove_nixpkgsissue_comment_remove_nixpkgsissue_cve_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachednixpkgsissue',
            name='issue',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='nixpkgsissue',
            name='pgpubsub_caec7',
        ),
        migrations.DeleteModel(
            name='CachedNixpkgsIssue',
        ),
    ]
