# Generated by Django 4.2.24 on 2025-12-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0063_remove_cachednixpkgsissue_issue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nixpkgsissue',
            name='derivations',
        ),
    ]
