# Generated by Django 5.2.6 on 2026-01-19 10:42

import django
import shared.models.issue
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0064_remove_cvederivationclusterproposal_pgpubsub_6aede_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nixpkgsevent',
            name='reference',
        ),
        migrations.AddField(
            model_name='nixpkgsevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nixpkgsevent',
            name='event_type',
            field=models.IntegerField(validators=[shared.models.issue.EventType.validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nixpkgsevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nixpkgsevent',
            name='url',
            field=models.URLField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nixpkgsevent',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shared.nixpkgsissue'),
        ),
    ]
