# Generated by Django 5.2.6 on 2026-01-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0065_remove_nixpkgsevent_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nixpkgsissue',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
