# Generated by Django 5.2.6 on 2026-01-29 17:31

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0066_alter_nixpkgsissue_code'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='nixchannel',
            name='pgpubsub_ae5b1',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nixchannel',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_3c4a2', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; notification_context_text TEXT;', func='\n            \n            payload := \'{"app": "shared", "model": "NixChannel"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.notification_context\', True) INTO notification_context_text;\n            IF COALESCE(notification_context_text, \'\') = \'\' THEN\n                notification_context_text := \'{}\';\n            END IF;\n            payload := jsonb_insert(payload, \'{context}\', notification_context_text::jsonb);\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_3c4a2\', payload);\n        \n            perform pg_notify(\'pgpubsub_3c4a2\', payload::text);\n            RETURN NEW;\n        ', hash='614cb3b1afd2ec3c4d3d77c17a3ec1a6080aa8d0', operation='INSERT', pgid='pgtrigger_pgpubsub_3c4a2_e45b2', table='shared_nixchannel', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='nixchannel',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_f33a1', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; notification_context_text TEXT;', func='\n            \n            payload := \'{"app": "shared", "model": "NixChannel"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.notification_context\', True) INTO notification_context_text;\n            IF COALESCE(notification_context_text, \'\') = \'\' THEN\n                notification_context_text := \'{}\';\n            END IF;\n            payload := jsonb_insert(payload, \'{context}\', notification_context_text::jsonb);\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_f33a1\', payload);\n        \n            perform pg_notify(\'pgpubsub_f33a1\', payload::text);\n            RETURN NEW;\n        ', hash='e3d38d5d3cd71f82bcef1553da8052d975beb31a', operation='UPDATE', pgid='pgtrigger_pgpubsub_f33a1_f3dfd', table='shared_nixchannel', when='AFTER')),
        ),
    ]
