# Generated by Django 5.2.9 on 2026-03-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0070_cvederivationclusterproposal_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvederivationclusterproposal',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('exclusively_hosted_service', 'exclusively hosted service'), ('not_in_nixpkgs', 'not in nixpkgs')], help_text='Reason for rejection (automatic or manual)', max_length=126, null=True),
        ),
    ]
