# Generated by Django 5.2.9 on 2026-03-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0070_cvederivationclusterproposal_rejection_reason'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.CheckConstraint(check=models.Q(('base_score__gte', 0.0), ('base_score__lte', 10.0)), name='metric_base_score_range'),
        ),
    ]
