# Generated by Django 5.2.9 on 2026-03-20 15:19

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0071_metric_metric_base_score_range'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='cvederivationclusterproposal',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='cvederivationclusterproposal',
            name='update_update',
        ),
        migrations.AddField(
            model_name='cvederivationclusterproposalstatusevent',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('exclusively_hosted_service', 'exclusively hosted service'), ('not_in_nixpkgs', 'not in Nixpkgs')], help_text='Reason for rejection (automatic or manual)', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='cvederivationclusterproposal',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('exclusively_hosted_service', 'exclusively hosted service'), ('not_in_nixpkgs', 'not in Nixpkgs')], help_text='Reason for rejection (automatic or manual)', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='cvederivationclusterproposalstatusevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_rejection_reason_events', to='shared.cvederivationclusterproposal'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cvederivationclusterproposal',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "shared_cvederivationclusterproposalstatusevent" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rejection_reason", "status") VALUES (_pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."rejection_reason", NEW."status"); RETURN NULL;', hash='58c7e498b7857177d7a4a65a98a17e0b4329da61', operation='INSERT', pgid='pgtrigger_insert_insert_d1e55', table='shared_cvederivationclusterproposal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cvederivationclusterproposal',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."rejection_reason" IS DISTINCT FROM (NEW."rejection_reason") OR OLD."status" IS DISTINCT FROM (NEW."status"))', func='INSERT INTO "shared_cvederivationclusterproposalstatusevent" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rejection_reason", "status") VALUES (_pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."rejection_reason", NEW."status"); RETURN NULL;', hash='f96194d4e357edcae4e6c8956cb8e87a5d1596d1', operation='UPDATE', pgid='pgtrigger_update_update_b6b2c', table='shared_cvederivationclusterproposal', when='AFTER')),
        ),
    ]
