# Generated by Django 5.2.9 on 2026-03-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0072_remove_cvederivationclusterproposal_insert_insert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectedproduct',
            name='default_status',
            field=models.CharField(choices=[('affected', 'affected'), ('unaffected', 'unaffected'), ('unknown', 'unknown')], default='unknown', max_length=126),
        ),
        migrations.AlterField(
            model_name='credit',
            name='_type',
            field=models.CharField(choices=[('finder', 'finder'), ('reporter', 'reporter'), ('analyst', 'analyst'), ('coordinator', 'coordinator'), ('remediation developer', 'remediation developer'), ('remediation reviewer', 'remediation reviewer'), ('remediation verifier', 'remediation_verifier'), ('tool', 'tool'), ('sponsor', 'sponsor'), ('other', 'other')], default='finder', max_length=126),
        ),
        migrations.AlterField(
            model_name='cvederivationclusterproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('accepted', 'accepted'), ('published', 'published')], default='pending', max_length=126),
        ),
        migrations.AlterField(
            model_name='cvederivationclusterproposalstatusevent',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('accepted', 'accepted'), ('published', 'published')], default='pending', max_length=126),
        ),
        migrations.AlterField(
            model_name='cverecord',
            name='state',
            field=models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('REJECTED', 'REJECTED')], default='PUBLISHED', max_length=126),
        ),
        migrations.AlterField(
            model_name='maintainersedit',
            name='edit_type',
            field=models.CharField(choices=[('add', 'add'), ('remove', 'remove')], max_length=126),
        ),
        migrations.AlterField(
            model_name='maintainerseditevent',
            name='edit_type',
            field=models.CharField(choices=[('add', 'add'), ('remove', 'remove')], max_length=126),
        ),
        migrations.AlterField(
            model_name='metric',
            name='attack_complexity',
            field=models.CharField(choices=[('NONE', 'NONE'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default=None, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='attack_vector',
            field=models.CharField(choices=[('PHYSICAL', 'PHYSICAL'), ('LOCAL', 'LOCAL'), ('ADJACENT_NETWORK', 'ADJACENT_NETWORK'), ('NETWORK', 'NETWORK')], default=None, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='availability_impact',
            field=models.CharField(choices=[('NONE', 'NONE'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default=None, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='base_severity',
            field=models.CharField(choices=[('NONE', 'NONE'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default=None, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='confidentiality_impact',
            field=models.CharField(choices=[('NONE', 'NONE'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default=None, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='integrity_impact',
            field=models.CharField(choices=[('NONE', 'NONE'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default=None, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='privileges_required',
            field=models.CharField(choices=[('NONE', 'NONE'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default=None, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='scope',
            field=models.CharField(choices=[('UNCHANGED', 'UNCHANGED'), ('CHANGED', 'CHANGED')], default=None, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='user_interaction',
            field=models.CharField(choices=[('NONE', 'NONE'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default=None, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='nixchannel',
            name='state',
            field=models.CharField(choices=[('END_OF_LIFE', 'End of life'), ('DEPRECATED', 'Deprecated'), ('BETA', 'Beta'), ('STABLE', 'Stable'), ('UNSTABLE', 'Unstable'), ('STAGING', 'Staging')], max_length=126),
        ),
        migrations.AlterField(
            model_name='nixevaluation',
            name='state',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('WAITING', 'Waiting to be started'), ('IN_PROGRESS', 'In progress'), ('CRASHED', 'Crashed'), ('FAILED', 'Failed')], max_length=126),
        ),
        migrations.AlterField(
            model_name='nixpkgsissue',
            name='status',
            field=models.CharField(choices=[('U', 'unknown'), ('A', 'affected'), ('NA', 'notaffected'), ('O', 'notforus'), ('W', 'wontfix')], default='U', max_length=126),
        ),
        migrations.AlterField(
            model_name='packageedit',
            name='edit_type',
            field=models.CharField(choices=[('remove', 'remove')], max_length=126),
        ),
        migrations.AlterField(
            model_name='packageeditevent',
            name='edit_type',
            field=models.CharField(choices=[('remove', 'remove')], max_length=126),
        ),
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.CharField(choices=[('affected', 'affected'), ('unaffected', 'unaffected'), ('unknown', 'unknown')], default='unknown', max_length=126),
        ),
    ]
