# Generated by Django 5.2.9 on 2026-03-22 17:16

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0072_remove_cvederivationclusterproposal_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='cvederivationclusterproposal',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='cvederivationclusterproposal',
            name='update_update',
        ),
        migrations.AlterField(
            model_name='affectedproduct',
            name='default_status',
            field=models.CharField(choices=[('affected', 'affected'), ('unaffected', 'unaffected'), ('unknown', 'unknown')], default='unknown', max_length=126),
        ),
        migrations.AlterField(
            model_name='credit',
            name='_type',
            field=models.CharField(choices=[('finder', 'finder'), ('reporter', 'reporter'), ('analyst', 'analyst'), ('coordinator', 'coordinator'), ('remediation developer', 'remediation developer'), ('remediation reviewer', 'remediation reviewer'), ('remediation verifier', 'remediation_verifier'), ('tool', 'tool'), ('sponsor', 'sponsor'), ('other', 'other')], default='finder', max_length=126),
        ),
        migrations.AlterField(
            model_name='cvederivationclusterproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('accepted', 'accepted'), ('published', 'published')], default='pending', max_length=126),
        ),
        migrations.AlterField(
            model_name='cvederivationclusterproposalstatusevent',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('accepted', 'accepted'), ('published', 'published')], default='pending', max_length=126),
        ),
        migrations.AlterField(
            model_name='cverecord',
            name='state',
            field=models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('REJECTED', 'REJECTED')], default='PUBLISHED', max_length=126),
        ),
        migrations.AlterField(
            model_name='maintainersedit',
            name='edit_type',
            field=models.CharField(choices=[('add', 'add'), ('remove', 'remove')], max_length=126),
        ),
        migrations.AlterField(
            model_name='maintainerseditevent',
            name='edit_type',
            field=models.CharField(choices=[('add', 'add'), ('remove', 'remove')], max_length=126),
        ),
        migrations.AlterField(
            model_name='metric',
            name='attack_complexity',
            field=models.CharField(choices=[('NONE', 'NONE'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default=None, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='attack_vector',
            field=models.CharField(choices=[('PHYSICAL', 'PHYSICAL'), ('LOCAL', 'LOCAL'), ('ADJACENT_NETWORK', 'ADJACENT_NETWORK'), ('NETWORK', 'NETWORK')], default=None, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='availability_impact',
            field=models.CharField(choices=[('NONE', 'NONE'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default=None, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='base_severity',
            field=models.CharField(choices=[('NONE', 'NONE'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default=None, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='confidentiality_impact',
            field=models.CharField(choices=[('NONE', 'NONE'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default=None, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='integrity_impact',
            field=models.CharField(choices=[('NONE', 'NONE'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default=None, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='privileges_required',
            field=models.CharField(choices=[('NONE', 'NONE'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default=None, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='scope',
            field=models.CharField(choices=[('UNCHANGED', 'UNCHANGED'), ('CHANGED', 'CHANGED')], default=None, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='user_interaction',
            field=models.CharField(choices=[('NONE', 'NONE'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default=None, max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='nixchannel',
            name='state',
            field=models.CharField(choices=[('END_OF_LIFE', 'End of life'), ('DEPRECATED', 'Deprecated'), ('BETA', 'Beta'), ('STABLE', 'Stable'), ('UNSTABLE', 'Unstable'), ('STAGING', 'Staging')], max_length=126),
        ),
        migrations.AlterField(
            model_name='nixevaluation',
            name='state',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('WAITING', 'Waiting to be started'), ('IN_PROGRESS', 'In progress'), ('CRASHED', 'Crashed'), ('FAILED', 'Failed')], max_length=126),
        ),
        migrations.AlterField(
            model_name='nixpkgsissue',
            name='status',
            field=models.CharField(choices=[('U', 'unknown'), ('A', 'affected'), ('NA', 'notaffected'), ('O', 'notforus'), ('W', 'wontfix')], default='U', max_length=126),
        ),
        migrations.AlterField(
            model_name='packageedit',
            name='edit_type',
            field=models.CharField(choices=[('remove', 'remove')], max_length=126),
        ),
        migrations.AlterField(
            model_name='packageeditevent',
            name='edit_type',
            field=models.CharField(choices=[('remove', 'remove')], max_length=126),
        ),
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.CharField(choices=[('affected', 'affected'), ('unaffected', 'unaffected'), ('unknown', 'unknown')], default='unknown', max_length=126),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cvederivationclusterproposal',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "shared_cvederivationclusterproposalstatusevent" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rejection_reason", "status") VALUES (_pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."rejection_reason", NEW."status"); RETURN NULL;', hash='58c7e498b7857177d7a4a65a98a17e0b4329da61', operation='INSERT', pgid='pgtrigger_insert_insert_d1e55', table='shared_cvederivationclusterproposal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cvederivationclusterproposal',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."rejection_reason" IS DISTINCT FROM (NEW."rejection_reason") OR OLD."status" IS DISTINCT FROM (NEW."status"))', func='INSERT INTO "shared_cvederivationclusterproposalstatusevent" ("pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "rejection_reason", "status") VALUES (_pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."rejection_reason", NEW."status"); RETURN NULL;', hash='f96194d4e357edcae4e6c8956cb8e87a5d1596d1', operation='UPDATE', pgid='pgtrigger_update_update_b6b2c', table='shared_cvederivationclusterproposal', when='AFTER')),
        ),
    ]
