# Generated by Django 5.2.9 on 2026-03-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0073_alter_affectedproduct_default_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvederivationclusterproposal',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('exclusively_hosted_service', 'exclusively hosted service'), ('not_in_nixpkgs', 'not in Nixpkgs'), ('hardware_only_cpe', 'hardware only CPE')], help_text='Reason for rejection (automatic or manual)', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='cvederivationclusterproposalstatusevent',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('exclusively_hosted_service', 'exclusively hosted service'), ('not_in_nixpkgs', 'not in Nixpkgs'), ('hardware_only_cpe', 'hardware only CPE')], help_text='Reason for rejection (automatic or manual)', max_length=126, null=True),
        ),
    ]
