# Generated by Django 5.2.9 on 2026-03-31 15:26

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('shared', '0075_alter_cvederivationclusterproposal_rejection_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ignored', 'ignored')], max_length=126)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.reference')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_overlays', to='shared.cvederivationclusterproposal')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceOverlayEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('type', models.CharField(choices=[('ignored', 'ignored')], max_length=126)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='shared.referenceoverlay')),
                ('reference', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='shared.reference')),
                ('suggestion', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='shared.cvederivationclusterproposal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='referenceoverlay',
            constraint=models.UniqueConstraint(fields=('suggestion', 'reference'), name='unique_reference_overlay_per_suggestion'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referenceoverlayevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='9215de3095dcefbd1369fa1389c94ebe3a5a1167', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_61285', table='shared_referenceoverlayevent', when='BEFORE')),
        ),
    ]
