# Generated by Django 5.2.9 on 2026-03-25 19:03

import pgtrigger.compiler
import pgtrigger.migrations
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        ('shared', '0076_referenceoverlay_referenceoverlayevent_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaintainersEdit',
            new_name='MaintainerOverlay',
        ),
        migrations.RenameModel(
            old_name='PackageEdit',
            new_name='PackageOverlay',
        ),
        migrations.AlterField(
            model_name='maintaineroverlay',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintainer_overlays', to='shared.cvederivationclusterproposal'),
        ),
        migrations.AlterField(
            model_name='packageoverlay',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_overlays', to='shared.cvederivationclusterproposal'),
        ),
        migrations.RenameModel(
            old_name='MaintainersEditEvent',
            new_name='MaintainerOverlayEvent',
        ),
        migrations.RenameModel(
            old_name='PackageEditEvent',
            new_name='PackageOverlayEvent',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='maintaineroverlayevent',
            name='append_only',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='packageoverlayevent',
            name='append_only',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='maintaineroverlayevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='14c983337ff6aba25adee63596ad595ebc7addc0', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_57b9c', table='shared_maintaineroverlayevent', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='packageoverlayevent',
            trigger=pgtrigger.compiler.Trigger(name='append_only', sql=pgtrigger.compiler.UpsertTriggerSql(func="RAISE EXCEPTION 'pgtrigger: Cannot update or delete rows from % table', TG_TABLE_NAME;", hash='f805545d1a2028c9aa53955c61c9f2df72d9e44b', operation='UPDATE OR DELETE', pgid='pgtrigger_append_only_c0ffc', table='shared_packageoverlayevent', when='BEFORE')),
        ),

         migrations.RemoveConstraint(
            model_name='maintaineroverlay',
            name='unique_maintainer_edit_per_suggestion',
        ),
        migrations.RemoveConstraint(
            model_name='packageoverlay',
            name='unique_package_edit_per_suggestion',
        ),
        migrations.AddConstraint(
            model_name='maintaineroverlay',
            constraint=models.UniqueConstraint(fields=('suggestion', 'maintainer'), name='unique_maintainer_overlay_per_suggestion'),
        ),
        migrations.AddConstraint(
            model_name='packageoverlay',
            constraint=models.UniqueConstraint(fields=('suggestion', 'package_attribute'), name='unique_package_overlay_per_suggestion'),
        ),
    ]
