# Generated by Django 5.2.9 on 2026-03-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0077_rename_maintainersedit_and_packageedit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedsuggestions',
            name='schema_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
