# Generated by Django 5.2.9 on 2026-04-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0078_cachedsuggestions_schema_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintaineroverlay',
            name='edit_type',
            field=models.CharField(choices=[('additional', 'additional'), ('ignored', 'ignored')], max_length=126),
        ),
        migrations.AlterField(
            model_name='maintaineroverlayevent',
            name='edit_type',
            field=models.CharField(choices=[('additional', 'additional'), ('ignored', 'ignored')], max_length=126),
        ),
        migrations.AlterField(
            model_name='packageoverlay',
            name='edit_type',
            field=models.CharField(choices=[('ignored', 'ignored')], max_length=126),
        ),
        migrations.AlterField(
            model_name='packageoverlayevent',
            name='edit_type',
            field=models.CharField(choices=[('ignored', 'ignored')], max_length=126),
        ),
    ]
