# Generated by Django 5.2.9 on 2026-04-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0079_alter_maintaineroverlay_edit_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintaineroverlay',
            old_name='edit_type',
            new_name='overlay_type',
        ),
        migrations.RenameField(
            model_name='maintaineroverlayevent',
            old_name='edit_type',
            new_name='overlay_type',
        ),
        migrations.RenameField(
            model_name='packageoverlay',
            old_name='edit_type',
            new_name='overlay_type',
        ),
        migrations.RenameField(
            model_name='packageoverlayevent',
            old_name='edit_type',
            new_name='overlay_type',
        ),
    ]
