# Generated by Django 5.2.9 on 2026-04-16 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0081_remove_referenceoverlayevent_pgh_obj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivationclusterproposallink',
            name='derivation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shared.nixderivation'),
        ),
        migrations.AlterField(
            model_name='maintaineroverlay',
            name='maintainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shared.nixmaintainer'),
        ),
        migrations.AlterField(
            model_name='nixderivation',
            name='parent_evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivations', to='shared.nixevaluation'),
        ),
        migrations.AlterField(
            model_name='nixevaluation',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='shared.nixchannel'),
        ),
    ]
