# Generated by Django 5.2.12 on 2026-05-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0083_remove_cvederivationclusterproposal_pgpubsub_07e32_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvederivationclusterproposal',
            name='algorithm_version',
            field=models.IntegerField(default=1, help_text='Version of the matching algorithm that generated this proposal'),
        ),
    ]
