# Generated by Django 5.2.12 on 2026-05-05 12:30

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0083_remove_cvederivationclusterproposal_pgpubsub_07e32_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvederivationclusterproposal',
            name='comment',
            field=models.CharField(blank=True, help_text='Optional free text comment for additional notes, context, dismissal reason', max_length=1000, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='cvederivationclusterproposal',
            trigger=pgtrigger.compiler.Trigger(name='status_fsm', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE _is_valid_transition BOOLEAN;', func='SELECT CONCAT(OLD."status", \':\', NEW."status") = ANY(\'{pending:rejected,pending:accepted,rejected:accepted,accepted:rejected,accepted:published,accepted:pending,rejected:pending}\'::text[]) INTO _is_valid_transition; IF (_is_valid_transition IS FALSE AND OLD."status" IS DISTINCT FROM NEW."status") THEN RAISE EXCEPTION \'pgtrigger: Invalid transition of field "status" from "%" to "%" on table %\', OLD."status", NEW."status", TG_TABLE_NAME; ELSE RETURN NEW; END IF;', hash='cde62ddb489a9102f84b06148d456e8c9688f61e', operation='UPDATE', pgid='pgtrigger_status_fsm_c5468', table='shared_cvederivationclusterproposal', when='BEFORE')),
        ),
    ]
