# Generated by Django 5.2.12 on 2026-05-06 15:12

from django.db import migrations

def delete_invalid_metrics(apps, schema_editor):
    Metric = apps.get_model("shared", "Metric")
    Metric.objects.filter(vector_string__isnull=True).delete()
    Metric.objects.filter(vector_string="").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0084_cvederivationclusterproposal_status_fsm'),
    ]

    operations = [
        migrations.RunPython(delete_invalid_metrics, migrations.RunPython.noop),
    ]
