# Generated by Django 5.2.12 on 2026-05-06 15:12

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0085_delete_metrics_with_empty_vector_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='vector_string',
            field=models.CharField(max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metric',
            name='format',
            field=models.CharField(choices=[('cvssV4_0', '4.0'), ('cvssV3_1', '3.1'), ('cvssV3_0', '3.0')], max_length=64),
        ),

        # We remove everything else, since it can be recomputed from the above.
        migrations.RemoveField(
            model_name='metric',
            name='attack_complexity',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='attack_vector',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='availability_impact',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='confidentiality_impact',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='integrity_impact',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='privileges_required',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='raw_cvss_json',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='scenarios',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='user_interaction',
        ),
        migrations.RemoveConstraint(
            model_name='metric',
            name='metric_base_score_range',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='base_score',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='base_severity',
        ),
        migrations.DeleteModel(
            name='Impact',
        ),
    ]
