# Generated by Django 5.2.12 on 2026-05-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0087_cvederivationclusterproposal_algorithm_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvederivationclusterproposal',
            name='in_issue_draft',
            field=models.BooleanField(default=False),
        ),
    ]
