# Generated by Django 5.2.9 on 2026-04-28 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0087_cvederivationclusterproposal_algorithm_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
                ('homepage', models.URLField(null=True)),
                ('description', models.TextField(null=True)),
                ('maintainers', models.ManyToManyField(to='shared.nixmaintainer')),
            ],
        ),
        migrations.CreateModel(
            name='PackageAttrpath',
            fields=[
                ('pk', models.CompositePrimaryKey('package', 'attrpath', blank=True, editable=False, primary_key=True, serialize=False)),
                ('attrpath', models.CharField(max_length=255, unique=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrpaths', to='shared.package')),
            ],
        ),
        migrations.CreateModel(
            name='PackageDerivation',
            fields=[
                ('derivation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='package_link', serialize=False, to='shared.nixderivation')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivations', to='shared.package')),
            ],
        ),
    ]
