# Generated by Django 5.2.12 on 2026-05-22 19:43

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0088_package_nixderivation_package_packageattrpath'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='nixderivationmeta',
            name='description_search_vector_idx',
        ),
        migrations.RemoveIndex(
            model_name='nixderivationmeta',
            name='shared_nixd_search__c5ba7b_gin',
        ),
        migrations.RemoveField(
            model_name='nixderivationmeta',
            name='search_vector',
        ),
        migrations.AddField(
            model_name='package',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='package',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='shared_pack_search__728871_gin'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='package',
            trigger=pgtrigger.compiler.Trigger(name='description_search_vector_idx', sql=pgtrigger.compiler.UpsertTriggerSql(execute='tsvector_update_trigger("search_vector", "pg_catalog.english", "description")', func='', hash='6a43361db3c386e41ec0a32d7426a4a809f5bce7', operation='INSERT OR UPDATE OF "description"', pgid='pgtrigger_description_search_vector_idx_8e721', table='shared_package', when='BEFORE')),
        ),
    ]
