# Generated by Django 5.2.14 on 2026-06-01 16:05

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0090_remove_nixpkgsissue_suggestion_and_more'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='nixevaluation',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_6af0c', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; notification_context_text TEXT;', func='\n            \n            payload := \'{"app": "shared", "model": "NixEvaluation"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.notification_context\', True) INTO notification_context_text;\n            IF COALESCE(notification_context_text, \'\') = \'\' THEN\n                notification_context_text := \'{}\';\n            END IF;\n            payload := jsonb_insert(payload, \'{context}\', notification_context_text::jsonb);\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_6af0c\', payload);\n        \n            perform pg_notify(\'pgpubsub_6af0c\', payload::text);\n            RETURN NEW;\n        ', hash='7b6700160a17a687708bf7b9086974c872ba51b0', operation='UPDATE', pgid='pgtrigger_pgpubsub_6af0c_9d405', table='shared_nixevaluation', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(fields=('name', 'homepage'), name='package_name_homepage_unique', nulls_distinct=False),
        ),
    ]
