# Generated by Django 5.2.14 on 2026-06-12 16:55

from django.db import migrations, models


_STATE_MAP = {
    "END_OF_LIFE": "unmaintained",
    "DEPRECATED": "deprecated",
    "BETA": "beta",
    "STABLE": "stable",
    "UNSTABLE": "rolling",
}


def remap_channel_states(apps, schema_editor):
    NixChannel = apps.get_model("shared", "NixChannel")
    for old, new in _STATE_MAP.items():
        NixChannel.objects.filter(state=old).update(state=new)


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0091_nixevaluation_pgpubsub_6af0c_and_more'),
    ]

    operations = [
        migrations.RunPython(remap_channel_states, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='nixchannel',
            name='release_version',
        ),
        migrations.RenameField(
            model_name='nixchannel',
            old_name='staging_branch',
            new_name='release_branch',
        ),
        migrations.AlterField(
            model_name='nixchannel',
            name='state',
            field=models.CharField(choices=[('unmaintained', 'End of life'), ('deprecated', 'Deprecated'), ('beta', 'Beta'), ('stable', 'Stable'), ('rolling', 'Unstable')], max_length=126),
        ),
    ]
