# Generated by Django 5.2.14 on 2026-06-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0092_remove_nixchannel_release_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvederivationclusterproposal',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('exclusively_hosted_service', 'exclusively hosted service'), ('not_in_nixpkgs', 'not in Nixpkgs'), ('hardware_only_cpe', 'hardware only'), ('known_vulnerability', 'already tracked in derivation metadata')], help_text='Reason for rejection (automatic or manual)', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='cvederivationclusterproposalstatusevent',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('exclusively_hosted_service', 'exclusively hosted service'), ('not_in_nixpkgs', 'not in Nixpkgs'), ('hardware_only_cpe', 'hardware only'), ('known_vulnerability', 'already tracked in derivation metadata')], help_text='Reason for rejection (automatic or manual)', max_length=126, null=True),
        ),
    ]
