# Generated by Django 5.2.14 on 2026-06-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0093_alter_cvederivationclusterproposal_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nixevaluation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='nixevaluation',
            constraint=models.UniqueConstraint(fields=('commit_sha1',), name='nixevaluation_commit_sha1_unique'),
        ),
    ]
