# Generated by Django 5.2.14 on 2026-06-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0094_alter_nixevaluation_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvederivationclusterproposal",
            name="rejection_match_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cvederivationclusterproposal",
            name="rejection_max_matches_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cvederivationclusterproposal",
            name="rejection_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("exclusively_hosted_service", "exclusively hosted service"),
                    ("not_in_nixpkgs", "not in Nixpkgs"),
                    ("hardware_only_cpe", "hardware only"),
                    ("max_matches_exceeded", "max. allowed matches exceeded"),
                    ("known_vulnerability", "already tracked in derivation metadata"),
                ],
                help_text="Reason for rejection (automatic or manual)",
                max_length=126,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cvederivationclusterproposalstatusevent",
            name="rejection_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("exclusively_hosted_service", "exclusively hosted service"),
                    ("not_in_nixpkgs", "not in Nixpkgs"),
                    ("hardware_only_cpe", "hardware only"),
                    ("max_matches_exceeded", "max. allowed matches exceeded"),
                    ("known_vulnerability", "already tracked in derivation metadata"),
                ],
                help_text="Reason for rejection (automatic or manual)",
                max_length=126,
                null=True,
            ),
        ),
    ]
