# Generated by Django 5.2.14 on 2026-06-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0095_max_matches_exceeded_rejection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvederivationclusterproposal',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('exclusively_hosted_service', 'exclusively hosted service'), ('not_in_nixpkgs', 'not in Nixpkgs'), ('hardware_only_cpe', 'hardware only'), ('max_matches_exceeded', 'max. allowed matches exceeded'), ('known_vulnerability', 'already tracked in derivation metadata'), ('no_matches', 'no matching packages found')], help_text='Reason for rejection (automatic or manual)', max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='cvederivationclusterproposalstatusevent',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('exclusively_hosted_service', 'exclusively hosted service'), ('not_in_nixpkgs', 'not in Nixpkgs'), ('hardware_only_cpe', 'hardware only'), ('max_matches_exceeded', 'max. allowed matches exceeded'), ('known_vulnerability', 'already tracked in derivation metadata'), ('no_matches', 'no matching packages found')], help_text='Reason for rejection (automatic or manual)', max_length=126, null=True),
        ),
    ]
