# Generated by Django 5.2.15 on 2026-07-22 10:00
from django.db import migrations


def insert_matching_training_data_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    # Limited set of users who may fetch matching training data.
    # Membership is assigned manually, stopgap until rate limiting exists.
    Group.objects.get_or_create(name="matching_training_data")


def remove_matching_training_data_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="matching_training_data").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0101_nixpkgsbranch_nixchannel_release_branch"),
    ]

    operations = [
        migrations.RunPython(
            insert_matching_training_data_group,
            remove_matching_training_data_group,
        ),
    ]
